# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
favicon: /favicon.ico

version: 0.0.1

# Duoshuo 
duoshuo:
	shortname: helkyle
	share: 
		weixin
		weibo

excerpt_link: 更多...
excerpt_length: 600

banner-url: 'https://unsplash.it/1400/600/?gravity=west&image=685'