# Header
menu:
  主页: /
  归档: /archives
  标签: /tags
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
favicon: /favicon.ico

version: 0.0.1

#头像url
avatar_url: http://7xlkda.com1.z0.glb.clouddn.com/avatar_helkyle.png

# Duoshuo 
duoshuo:
	shortname: helkyle
	share: 
		weixin
		weibo

excerpt_link: 更多...
excerpt_length: 600

banner-url: 'https://unsplash.it/1400/600/?gravity=west&image=685'