# Header
menu:
  主页: /
  归档: /archives
  标签: /tags
  关于: /about
  github: https://github.com/HelKyle/hexo-theme-helkyle
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico

version: 0.0.1

#放在header上的logo，正方形图片最佳
logo_img: http://7xlkda.com1.z0.glb.clouddn.com/helkyle-logo.png

# 多说
duoshuo:
	shortname: helkyle

#阅读更多文字以及最大长度
excerpt_link: 更多...
excerpt_length: 600

#打开fancybox
fancybox: true


#百度统计
baidu_tongji: 3640c17e94957cdf51170baa0f8f14e1

#Social
social:
# key weibo/twitter/google/github/stackoverflow/linkedin/facebook/codepen
# value url
# e.g github: https://github.com/helkyle
  github: https://github.com/helkyle
  weibo: http://weibo.com/joueu
  codepen: http://codepen.io/HelKyle/

#Footer Social
footer_social: 
  enable: false

#Article Social
author_meta:
  enable: true
  author_name: HelKyle
  # author_avatar: http://7xlkda.com1.z0.glb.clouddn.com/avatar_helkyle.png
  # 文章底部作者头像，非正方形也可以
  author_avatar: http://7xlkda.com1.z0.glb.clouddn.com/utah-thumb.gif
  social: true
  description: 我是周晓楷，一名小小程序员。

#blog since
since: 2014